Repository nlp-tlp/15926-4-RDL-CITS3200, pull requests merged in 2024-09, with the labels that each got.

#50 Fix client security vulnerability
  src/client/package-lock.json
  src/docker-compose.yml
Labels: frontend, security

#53 4 basic data retrieval and storage
  .github/workflows/qc-backend.yml
  .gitignore
  .husky/pre-commit
  .husky/pre-commit.example
  src/.env.example
  src/cli/__init__.py
  src/cli/cli.py
  src/cli/config.py
  src/cli/database.py
  src/cli/history.py
  src/db/config.yml
  src/docker-compose.yml
  src/server/app/config.py
  src/server/requirements.txt
  src/server/tests/conftest.py
Labels: enhancement, backend

#58 55 read children by id api endpoint
  README.md
  src/docker-compose.yml
  src/server/app/__init__.py
  src/server/app/config.py
  src/server/app/controllers.py
  src/server/app/models.py
  src/server/app/routes.py
  src/server/server.py
  src/server/tests/conftest.py
  src/server/tests/functional/test_database.py
  src/server/tests/functional/test_routes.py
  src/server/tests/unit/test_access-copy.py
  src/server/tests/unit/test_configuration.py
  src/server/tests/unit/test_controllers.py
Labels: enhancement, backend, deployment

#60 27 read info by id api endpoint
  src/server/app/controllers.py
  src/server/app/routes.py
  src/server/tests/conftest.py
  src/server/tests/functional/test_database.py
  src/server/tests/functional/test_routes.py
  src/server/tests/unit/test_controllers.py
Labels: documentation, backend

#61 Some RDF data was simulated for testing, and text wrapping and access…
  src/client/package-lock.json
  src/client/package.json
  src/client/src/components/GraphInfoSidepane.vue
  src/client/src/components/GraphSearchSidepane.vue
Labels: enhancement, frontend

#63 Hotfix 3 dependencies
  src/client/package-lock.json
  src/client/package.json
  src/docker-compose.yml
Labels: bug, frontend

#66 39 cli auto rollback
  src/cli/database.py
  src/cli/tests.py
  src/db/config.yml
Labels: enhancement, backend

#69 68 node organisation by alphabetical order
  src/server/app/controllers.py
  src/server/app/routes.py
Labels: enhancement, backend

#71 40 cli data versioning and help instructions
  README.md
  src/cli/cli.py
  src/cli/history.py
Labels: documentation, enhancement, backend

#78 64 search api endpoint
  src/server/app/config.py
  src/server/app/controllers.py
  src/server/app/models.py
  src/server/app/routes.py
  src/server/server.py
  src/server/tests/functional/test_search_routes.py
Labels: enhancement, backend

#80 Dynamic loading on node expansion
  src/client/package-lock.json
  src/client/src/components/GraphInfoSidepane.vue
  src/client/src/components/GraphSearchSidepane.vue
  src/client/src/components/GraphVisualisation.vue
  src/client/src/views/GraphView.vue
Labels: enhancement, frontend

#84 43 set up tailwind css for vue
  src/client/package-lock.json
  src/client/package.json
  src/client/postcss.config.js
  src/client/src/App.vue
  src/client/src/assets/base.css
  src/client/src/components/NavBar.vue
  src/client/src/components/NavBarItem.vue
  src/client/src/components/icons/IconDocumentation.vue
  src/client/src/components/icons/IconGraph.vue
  src/client/tailwind.config.js
  src/client/vite.config.ts
Labels: enhancement, frontend
