Repository nlp-tlp/15926-4-RDL-CITS3200, pull requests merged in 2024-10, with the labels that each got.

#87 86 relavent results in search
  src/client/src/components/GraphSearchSidepane.vue
  src/server/app/config.py
  src/server/app/controllers.py
  src/server/app/routes.py
  src/server/requirements.txt
  src/server/tests/functional/test_search_routes.py
Labels: frontend, backend

#91 74 styling pass
  src/client/index.html
  src/client/public/android-chrome-192x192.png
  src/client/public/android-chrome-512x512.png
  src/client/public/apple-touch-icon.png
  src/client/public/favicon-16x16.png
  src/client/public/favicon-32x32.png
  src/client/public/favicon.ico
  src/client/public/site.webmanifest
  src/client/src/components/NavBar.vue
  src/client/tests/e2e/navigation.test.ts
  src/client/tests/unit/components/NavBar.test.ts
Labels: bug, frontend

#82 28 graph export
  src/client/package-lock.json
  src/client/package.json
  src/client/src/assets/childrenGraphFunctions.ts
  src/client/src/assets/parentsGraphFunctions.ts
  src/client/src/components/GraphExport.vue
  src/client/src/components/GraphInfoSidepane.vue
  src/client/src/components/GraphSearchSidepane.vue
  src/client/src/components/GraphVisualisation.vue
  src/client/src/components/NavBar.vue
  src/client/src/components/icons/IconExport.vue
  src/client/src/views/GraphView.vue
Labels: enhancement, frontend
